# basic options
title: AHSURED
author: acomin
email: your-email@domain.com
description: Animal Health Surveillance Reporting Guidelines
twitter_username: none
github_username:  none

# Build settings
markdown: Markdown
theme: minima

#theme: jekyll-theme-minimal
