# basic options
title: AHSURED
author: acomin
email: ahsured@sva.se
description: Animal Health Surveillance Reporting Guidelines
twitter_username: none
github_username:  none

# Build settings
markdown: Markdown
theme: minima
plugins:
  - jemoji

#theme: jekyll-theme-minimal
